### ISSUE TITLE
Documentation How to Setup

### ISSUE THREAD

**Issue by valentin-debris** [bfn-tech/Matomo.Xamarin.Forms#1]
Hi, 

Thanks for this Nuget, we are planning to migrate from Analytics to Matomo and this comes at the right time ! 
I just have a small question, can you provide a quick documentation on How to Setup, to link this to a private Matomo instance ? We have a self hosted version for our websites, and I want to link the app to it.

Thanks

**Comment by bnoffer** [comment]
Hi @valentin-debris,

documentation will follow shortly, I am currently working on some quality of life improvements and documentation will come as part of that.

Best regards

**Comment by bnoffer** [comment]
Closing this issue since documentation has been added as part of Release v.1.1.0 .
